from typing import Protocol


class ControllerInterface(Protocol):
    def quit(self): ...
    def set_state(self, state): ...
    def open_file(self, filename): ...
    def save_file(self, filename): ...
    def help(self): ...
