from typing import Protocol

from app.editor.utils.keys import Key


class TextModel(Protocol):
    def insert(self, key): ...
    def get_lines(self): ...
    def get_cursor(self): ...
    def delete_line(self): ...
    def new_line(self, wrap: bool, above=False): ...
    def move_cursor_h(self, d: int): ...
    def move_cursor_v(self, d: int): ...
    def set_cursor(self, row: int | None, col: int | None): ...


class CommandModel(Protocol):
    def move_cursor(self, offset: int): ...
    def get_cursor_pos(self): ...
    def get_input_buffer(self): ...
    def set_input_buffer(self, value: str): ...
    def push_input_buffer(self, ch: Key | str): ...
    def get_mode(self): ...
    def set_mode(self, mode): ...
