from typing import Protocol

from app.editor.utils.keys import Key


class TextModel(Protocol):
    def insert(self, key): ...
    def delete(self, dir): ...
    def delete_word(self): ...
    def delete_next(self, forward): ...
    def get_lines(self): ...
    def get_cursor(self): ...
    def delete_line(self): ...
    def new_line(self, wrap: bool, above=False): ...
    def move_cursor_h(self, d: int): ...
    def move_cursor_v(self, d: int): ...
    def set_cursor(self, row: int | None, col: int | None): ...
    def load_file(self, filename: str, lines: list[str]): ...
    def move_cursor_word(self, forward: bool): ...
    def copy_line(self, line: bool): ...
    def paste(self): ...
    def search(self, reversed, query): ...
    def repeat_search(self, reversed): ...


class CommandModel(Protocol):
    def move_cursor(self, offset: int): ...
    def get_cursor_pos(self): ...
    def get_input_buffer(self): ...
    def set_input_buffer(self, value: str): ...
    def push_input_buffer(self, ch: Key | str): ...
    def get_mode(self): ...
    def set_mode(self, mode): ...
